### ISSUE TITLE
GLIBC_2.14 not found

### ISSUE THREAD

**Issue by realmbgl** [mesosphere/dcos-commons#1176]
When launching a pod with an image that is based on **centos6.6** it fails with the following in stderr.

```
ls: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /mnt/mesos/sandbox/libmesos-bundle/lib/libselinux.so.1)
ls: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /mnt/mesos/sandbox/libmesos-bundle/lib/libpcre.so.1)
ls: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /mnt/mesos/sandbox/libmesos-bundle/lib/libselinux.so.1)
ls: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /mnt/mesos/sandbox/libmesos-bundle/lib/libpcre.so.1)
```

Here a basic svc.yml that allows to reproduce this.

```
name: {{FRAMEWORK_NAME}}
scheduler:
  principal: {{FRAMEWORK_PRINCIPAL}}
pods:
  myfw:
    count: {{NODE_COUNT}}
    image: centos:6.6
    placement: {{NODE_PLACEMENT}}
    user: {{FRAMEWORK_USER}}
    {{#ENABLE_VIRTUAL_NETWORK}}
    networks:
      dcos:
    {{/ENABLE_VIRTUAL_NETWORK}}
    tasks:
      node:
        goal: RUNNING
        cmd: "echo myfw >> myfw-container-path/output && sleep $SLEEP_DURATION"
        cpus: {{NODE_CPUS}}
        memory: {{NODE_MEM}}
        volume:
          path: "myfw-container-path"
          type: {{NODE_DISK_TYPE}}
          size: {{NODE_DISK}}
        env:
          SLEEP_DURATION: {{SLEEP_DURATION}}
```
