### ISSUE TITLE
Tasks with goal of FINISHED never restart, even when the pod fails

### ISSUE THREAD

**Issue by philwinder** [mesosphere/dcos-commons#1631]
Cross-posting from https://jira.mesosphere.com/browse/DCOS_OSS-1544, as I'm not sure that's the right place for this.

---

AFAICS, the intended behaviour of a pod when a task is killed, or the pod is killed, is to restart the pod.
E.g.
> Restart entire pod when child containers crash or health checks fail.
 (https://mesosphere.com/blog/introducing-pods-dcos-1-9/)

I believe there is a bug in the edge case where the task goal is set to FINISHED, not RUNNING. When it is, the task with the goal FINISHED is never restarted when killing the other task or killing the pod.

# Use case

I want to run a script after an executable has started, as part of an init process. For example, some databases need run time commands to initialise it; this step cannot be performed in the static configuration. E.g. create users, create databases, etc.
I would need to run a plan like [[binary], [init]], where the init process only runs once when the binary first starts. If the binary is killed for whatever reason, the init script MUST run again.

# Recreate

To recreate, follow this example:
Alter the hello-world example/multistep-plan.yml file to make one of the tasks finish, rather than run continuously and don't forget to remove the healthcheck:
```
diff --git a/frameworks/helloworld/src/main/dist/examples/multistep_plan.yml b/frameworks/helloworld/src/main/dist/e
index c92ddde..615a0e7 100644
--- a/frameworks/helloworld/src/main/dist/examples/multistep_plan.yml
+++ b/frameworks/helloworld/src/main/dist/examples/multistep_plan.yml
@@ -26,8 +26,8 @@ pods:
           timeout: 10
           max-consecutive-failures: 3
       second:
-        goal: RUNNING
-        cmd: echo hello >> hello-container-path/output && sleep $SLEEP_DURATION
+        goal: FINISHED
+        cmd: echo hello >> hello-container-path/output
         cpus: {{HELLO_CPUS}}
         memory: {{HELLO_MEM}}
         volume:
@@ -36,13 +36,6 @@ pods:
           size: {{HELLO_DISK}}
         env:
           SLEEP_DURATION: {{SLEEP_DURATION}}
-        health-check:
-          cmd: stat hello-container-path/output
-          interval: 5
-          grace-period: 30
-          delay: 0
-          timeout: 10
-          max-consecutive-failures: 3
   world:
     count: {{WORLD_COUNT}}
     placement: {{WORLD_PLACEMENT}}
```

Next, build the hello-world framework and prepare to install on your cluster.

Finally, start the framework passing it a custom options json file to start the correct yml:

```
$ cat multistep-config.json 
{
"service": {
"spec_file": "examples/multistep_plan.yml"
}
} 
$ dcos package install --yes hello-world --options=multistep-config.json
...
```

Now, after you have waited for it to start, if you run the command: `dcos hello-world pod restart hello-0` OR you ssh into the agent and kill the pid of hello-0-first, then the hello-0-second will NOT get restarted. Killing the pod will only restart the first task.

---

Further info. I have just found out that this problem also affects tasks in other plans. For example, if I reuse tasks like this:

```
plans:
  deploy:
    strategy: serial
    phases:
      replicaset:
        strategy: parallel
        pod: mongo
        steps:
          - 0: [[mongod], [init]]
          - default: [[step-down], [mongod], [configure]]
  update:
    strategy: serial
    phases:
      replicaset:
        strategy: serial
        pod: mongo
        steps:
          - default: [[step-down], [mongod], [configure]]
```

And if you do an update, the step-down and configure tasks will not run for the first and second pods, because they have already run in the deploy plan.

---

Final update, if you run an update twice, nothing works. There is no workaround. For any task with a goal of FINISHED it will never be run again no matter what.
