### ISSUE TITLE
Are plans from YAML yet supported?

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#342]
I have the following definition in my YAML file, after the definition of the `mongodb` and `init` pods:

```yaml
plans:
  deploy:
    strategy: serial
    phases:
      mongodb-deploy:
        strategy: serial
        pod: mongodb
      init-deploy:
        strategy: serial
        pod: init
``` 

I was assuming that the `init` pod tasks would then be started **after** the `mongodb` pod's tasks, which is not the case.

Furthermore, if I use `goal: FINISHED` the tasks aren't even started! Is it even possible to start one-off tasks?
