### ISSUE TITLE
Health checks not working when defined via YAML?

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#414]
I tried to define a health check for a task in one of my framework's pods. Unfortunately, I can't see any health check activity in the task's logs, so it seems it doesn't work.

Here's the [definition](https://github.com/tobilg/dcos-commons/blob/mongodb-replicaset/frameworks/mongodb-replicaset/src/main/dist/svc.yml#L27) of my health check:

```yaml
health-check:
  name: "mongodb-server-health-check"
  cmd: "curl --fail ${LIBPROCESS_IP}:27017 > /dev/null"
  interval: 30
  grace-period: 60
  max-consecutive-failures: 5
  delay: 5
  timeout: 5
```

Is there something wrong with it? Thanks!
