### ISSUE TITLE
libmesos bundle interoperability issue

### ISSUE THREAD

**Issue by EronWright** [mesosphere/dcos-commons#509]
The libmesos bundle contains native libraries that clash with some Linux container environments. 
For example, the following pod (based on the well-known `java:8` image) fails:

```
  test:
    count: 1
    tasks:
      server:
        goal: FINISHED
        cmd: "wget https://dcos.io/"
        cpus: 1
        memory: 1024
    container:
      image-name: java:8
```

With the following error message in `stderr`:
```
wget: /mnt/mesos/sandbox/libmesos-bundle/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.52)
```

The damage is partly due to the fact that the bundle's libraries are placed onto the `LD_LIBRARY_PATH` and inherited by the task command.

One possible fix would be to avoid injecting the libmesos bundle when a container image is specified.   The JRE should probably not be injected in that situation either.   This would necessitate that the dependencies be preinstalled into the image.   Launch performance would improve as a side-effect.
